ARG BUILD_ENV="build:dev"
ARG SUITE_BRANCH=suite
ARG WALLET_BRANCH=suite
ARG EXPLORER_BRANCH=suite
FROM node:18 as stage-voting
ARG BUILD_ENV
WORKDIR /app/camino-suite-voting
COPY ./ /app/camino-suite-voting/
RUN yarn install
RUN yarn $BUILD_ENV
FROM 278308921038.dkr.ecr.eu-central-1.amazonaws.com/camino-suite-host:$SUITE_BRANCH as stage-suite
FROM 278308921038.dkr.ecr.eu-central-1.amazonaws.com/camino-suite-wallet:$WALLET_BRANCH  as stage-wallet
FROM 278308921038.dkr.ecr.eu-central-1.amazonaws.com/camino-suite-explorer:$EXPLORER_BRANCH  as stage-explorer
FROM nginx:1.18
COPY --from=stage-suite /app/camino-suite/dist/ /usr/share/nginx/html
COPY --from=stage-voting /app/camino-suite-voting/dist/ /usr/share/nginx/html/dac
COPY --from=stage-wallet /app/camino-wallet/dist/ /usr/share/nginx/html/wallet
COPY --from=stage-explorer /app/camino-block-explorer/dist/ /usr/share/nginx/html/explorer
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY ./nginx.conf /etc/nginx/conf.d/default.conf